blog/urls.py
# from django.urls import path
#
# import blog.views
#
# app_name = 'blog'
#
# urlpatterns = [
#     path("index/", blog.views.index, name="index"),
#     path("", blog.views.index, name="index"),
#     path("blog/detail/<int:blog_id>/", blog.views.blog_detail, name="blog_detail"),
#     path("blog/pub/", blog.views.pub_blog, name="pub_blog"),
#     path("blog/comment/pub/", blog.views.blog_comment, name="blog_comment"),
# ]


from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("index/", views.index, name="index"),
    path("", views.index, name="index"),
    path("blog/detail/<int:blog_id>/", views.blog_detail, name="blog_detail"),
    path("blog/pub/", views.pub_blog, name="pub_blog"),  # 确保URL以斜杠结尾
    path("blog/comment/pub/", views.blog_comment, name="blog_comment"),
    path("search/", views.search, name="search"),
]

zhiliaoblog/urls.py
from django.contrib import admin
from django.urls import path, include

import blog.views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('blog.urls')),
    path("auth/", include('zlauth.urls')),
    # path("blog/", include('blog.urls')),

]

zlauth/urls.py
from django.urls import path

from zlauth import views

app_name = 'zlauth'

urlpatterns = [
    path('login', views.zllogin, name='login'),
    path('register', views.register, name='register'),
    path('captcha', views.send_email_captcha, name='email_captcha'),
]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
User = get_user_model()
# Create your models here.

class BlogCategory(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name

class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='标题')
    content = models.TextField(verbose_name='内容')
    pub_time = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    category = models.ForeignKey(BlogCategory, on_delete=models.CASCADE, verbose_name='分类')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '博客'
        verbose_name_plural = verbose_name
        ordering = ['-pub_time']

class BlogComment(models.Model):
    content = models.TextField(verbose_name='内容')
    pub_time = models.DateTimeField(auto_now_add=True,)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments', verbose_name='所属博客')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['-pub_time']

zlauth/models.py
from django.db import models

# Create your models here.
class CaptchaModel(models.Model):
    email = models.EmailField(unique=True)
    captcha = models.CharField(max_length=4)
    create_time = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms


class PubBlogForm(forms.Form):
    title = forms.CharField(min_length=2, max_length=200)
    content = forms.CharField(min_length=2)
    category = forms.IntegerField()

zlauth/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20, min_length=2, error_messages={
        'required': '请传入用户名!',
        'min_length': '用户名长度在2~20之间!',
        'max_length': '用户名长度在2~20之间!'
    })
    email = forms.EmailField(error_messages={"required": '请传入邮箱!', 'invalid': '请传入一个正确的邮箱!'})
    captcha = forms.CharField(min_length=4, max_length=4)
    password = forms.CharField(min_length=6, max_length=20)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        exists = User.objects.filter(email=email).exists()
        if exists:
            raise forms.ValidationError('邮箱已经被注册!')
        return email

class LoginForm(forms.Form):
    email = forms.EmailField(error_messages={"required": '请传入邮箱!', 'invalid': '请传入一个正确的邮箱!'})
    password = forms.CharField(min_length=6, max_length=20)
    remember = forms.IntegerField(required=False)

blog/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect, reverse
from django.views.decorators.http import require_http_methods, require_POST, require_GET

from blog.forms import PubBlogForm
from blog.models import BlogCategory, Blog, BlogComment


# Create your views here.
def index(request):
    blogs = Blog.objects.all()
    return render(request, 'index.html', context={'blogs': blogs})

def blog_detail(request, blog_id):
    try:
        blog = Blog.objects.get(pk=blog_id)
    except Exception as e:
        blog = None
    return render(request, 'blog_detail.html', {'blog': blog})

@login_required()
def pub_blog(request):
    return render(request, 'pub_blog.html')


@require_http_methods(['GET', 'POST'])
@login_required()
def pub_blog(request):
    if request.method == 'GET':
        categories = BlogCategory.objects.all()
        return render(request, 'pub_blog.html', context={'categories': categories})
    else:
        form = PubBlogForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            category_id = form.cleaned_data['category']
            blog = Blog.objects.create(title=title, content=content, category_id=category_id, author=request.user)
            return JsonResponse({"code": 200, "message": "博客发布成功！", "data":{"blog_id": blog.id}})



@require_POST
@login_required()
def blog_comment(request):
    blog_id = request.POST.get('blog_id')
    content = request.POST.get('content')
    BlogComment.objects.create(blog_id=blog_id, content=content, author=request.user)
    return redirect(reverse('blog:blog_detail', kwargs={"blog_id":blog_id}))


@require_GET
def search(request):
    q = request.GET.get('q')
    blogs = Blog.objects.filter(Q(title__icontains=q)|Q(content__icontains=q)).all()
    return render(request, "../index.html", context={"blogs": blogs})

zlauth/views.py
import random
import string

from django.contrib.auth import get_user_model, login
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from zlauth.forms import RegisterForm, LoginForm
from zlauth.models import CaptchaModel

User = get_user_model()

# Create your views here.


def zllogin(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            remember = form.cleaned_data['remember']
            user = User.objects.filter(email=email).first()
            if user and user.check_password(password):
                # 登录
                login(request, user)

                # 判断是否需要记住我
                if not remember:
                    # 如果未点击记住我，设置过期时间为0
                    request.session.set_expiry(0)
                return redirect('/')
            else:
                print('邮箱或密码错误!')
                form.add_error('email', '邮箱或密码错误!')
                return render(request, 'login.html', context={'form': form})


@require_http_methods(['GET', 'POST'])
def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    else:
        form = RegisterForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            User.objects.create_user(username=username, email=email, password=password)
            return redirect(reverse('zlauth:login'))
        else:
            print(form.errors)
            return redirect(reverse('zlauth:register'))

def send_email_captcha(request):
    email = request.GET.get('email')
    if not email:
        return JsonResponse({"code": 400, "message": '必须传递邮箱！'})
    # 生成验证码
    captcha = "".join(random.sample(string.digits, 4))
    # 存储到数据库中
    CaptchaModel.objects.update_or_create(email=email, defaults={'captcha': captcha})
    send_mail("知了博客注册验证码", message=f"您的注册验证码是: {captcha}", from_email=None, recipient_list=[email])


    return JsonResponse({"code": 200, "message": "邮箱验证码发送成功！"})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}知了博客</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
{#顶部#}
<header class="p-3 text-bg-light border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            {#            <a href="/image/logo.png" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">#}
            {#              <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>#}
            {#            </a>#}

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
{#                <li><img src="{% static '/image/logo.png' %}" style="height: 30px"></li>#}
                <li><img src="/static/image/logo.png" style="height: 30px"></li>
                <li><a href="{% url 'blog:index' %}" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="{% url 'blog:pub_blog' %}" class="nav-link px-2 text-secondary">发布博客</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}"
                  method="get">
                <input type="search" name="q" class="form-control" placeholder="搜索..." aria-label="Search">
            </form>
            {# 判定登录状态/#}
            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        <img src="{% static 'image/face.png' %}" alt="mdo" width="32" height="32"
                             class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url 'zlauth:login' %}">退出登录</a></li>
                    </ul>
                </div>

            {% else %}

                <div class="text-end">
                    <a href="{% url 'zlauth:login' %}" type="button" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'zlauth:register' %}" type="button" class="btn btn-primary">注册</a>
                </div>
            {% endif %}


        </div>
    </div>
</header>
{#中间#}
<main class="container bg-white p-3 rounded">
    {% block main %} {% endblock %}

</main>
</body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="{% static 'highlight/styles/default.min.css' %}">
    <script src="{% static 'highlight/highlight.min.js' %}"></script>
{% endblock %}
{% block title %}{{ 知了博客首页 }}{% endblock %}
{% block main %}
    <h1>{{ blog.title }}</h1>
    <hr>
    {#    <div mt-2>#}
    <img class="rounded-circle" src="{% static 'image/face.png' %}" height="30px">
    <span class="ms-2">{{ blog.author.username }}</span>
    <span class="ms-2">于</span>
    <span class="ms-2">{{ blog.pub_time|date:"Y年m月d日 h时i分" }}</span>发布
    <hr>
    <div class="py-2">
        {{ blog.content|safe }}
    </div>
    <hr>
    <div class="mt-2">
        <h3>评论({{ blog.comments.all|length }})</h3>
        <form method="post" action="{% url 'blog:blog_comment' %}">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论" name="content">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary">评论</button>
            </div>
        </form>
    </div>
    <div class="mt-2">
        <ul class="list-group list-group-flush">
            {% for comment in blog.comments.all %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between text-body-secondary">
                        <div class="user-info">
                            <img class="rounded-circle" src="{% static 'image/face.png' %}" height="40px">
                            <span class="ms-2">{{ comment.author.username }}</span>
                        </div>
                        <div class="create-time"
                             style="line-height: 40px">{{ comment.pub_time|date:"Y年m月d日 h时i分" }}</div>
                    </div>
                    <div class="mt-3">{{ comment.content }}</div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <script>
        hljs.highlightAll()
    </script>

    {#    </div>#}
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}知了博客首页{% endblock %}

{% block main %}
    <h1>博客列表</h1>
    <div class="row row-cols-2 row-gap-3">
    {% for blog in blogs %}
    	<div class="col">
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'blog:blog_detail' blog_id=blog.id %}">{{ blog.title }}</a>
                </div>
                <div class="card-body" style="height: 100px">
                    <p class="card-text">{{ blog.content|striptags|truncatechars:200 }}</p>
                </div>
                <div class="card-footer text-muted d-flex justify-content-between">
                    <div class="p2">
                        <img class="rounded-circle" src="{% static 'image/face.png' %}" height="30px">
                        {{ blog.author.username }}
                    </div>
                    <div class="p2">{{ blog.pub_time|date:"Y年m月d日 h时i分" }}</div>
                </div>
            </div>
        </div>
    {% endfor %}
    
        
    
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}登录页{% endblock %}
{% block main %}
    <div style="max-width: 330px" class="m-auto">
        <h1>登录</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    记住我
                </label>
            </div>
            <div class="mb-3 d-grid">
                <button class="btn btn-primary">
                    登录
                </button>
            </div>
        </form>

    </div>
{% endblock %}

templates/pub_blog.html
{% extends 'base.html' %}

{% block title %}发布博客{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <style>
        #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
{% endblock %}

{% block main %}
    {% csrf_token %}
    <h1>发布博客</h1>
    <div class="mt-3">
        <form action="{% url 'blog:pub_blog' %}" method="post">
        {% csrf_token %}
            <div class="mb-3">
                <label class="form label">标题</label>
                <input type="text" name="title" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form label">分类</label>
                <select name="category" class="form-select">
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}

                </select>
            </div>
            <div class="mb-3">
                <label class="form label">内容</label>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-3 text-end">
                <button class="btn btn-primary" id="submit-btn">发布</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}
{% block title %}注册页{% endblock %}
{% block main %}
    <div style="max-width: 330px" class="m-auto">
        <h1>注册</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">

                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">

            </div>
            <div class="mb-3">

                <label>用户名</label>
                <input type="text" name="username" class="form-control" placeholder="用户名">
            </div>
            <div class="mb-3">
                <label>验证码</label>
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="验证码" aria-describedby="button-addon2"
                           name="captcha">
                    <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                </div>
            </div>

            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="mb-3">
                <button class="btn btn-primary w-100">注册</button>
            </div>
        </form>
    </div>
{% endblock %}